language: python
python:
- '2.7'
- '3.4'
- '3.5'
notifications:
  email: false
env:
  global:
  - GH_REF: github.com/ZELLMECHANIK-DRESDEN/dclab.git

before_install:
- wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- INSTALL_DIR=${HOME}
- ./miniconda.sh -b -p ${INSTALL_DIR}/miniconda
- export PATH=${INSTALL_DIR}/miniconda/bin:$PATH
- conda config --set always_yes yes --set changeps1 no
- travis_retry conda install -c "https://conda.binstar.org/menpo" python=$TRAVIS_PYTHON_VERSION pip numpy scipy cffi statsmodels opencv3
- travis_retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/fcswrite.git --no-deps
- travis_retry pip install .
install:
- travis_retry pip install coverage
- travis_retry pip install coveralls
- python setup.py develop
- pip freeze
script:
- coverage run --source=dclab ./setup.py test
- coverage report -m
after_success:
- coveralls --verbose

