language: python
python:
- '2.7'
- '3.4'
- '3.5'
notifications:
  email: false
before_install:
# Install binary packages
- travis_retry pip install --upgrade pip setuptools wheel
- travis_retry pip install --only-binary=numpy,pandas,scipy numpy pandas scipy
# Install fcswrite
- travis_retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/fcswrite.git --no-deps
# Install all other dependencies
- travis_retry pip install .
# Download ffmpeg (required by imageio)
- travis_retry python -c "import imageio; imageio.plugins.ffmpeg.download()"
install:
- travis_retry pip install coverage
- travis_retry pip install codecov
- python setup.py develop
- pip freeze
script:
- coverage run --source=dclab ./setup.py test
- coverage report -m
after_success:
- codecov

